name = "ctel-csdp-worker"
main = "src/index.js"
compatibility_date = "2026-03-25"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "csdp-db"
database_id = "fa983fef-907e-4e11-ab17-ce5496e68aac"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "9669de06286d422eba799db1ab8f933f"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "23275d53bf94428389da011e9b59919a"


[[queues.producers]]
binding = "NOTIFY_QUEUE"
queue = "notifications"

[vars]
APP_NAME = "Cyber Solution Delivery Platform"
APP_BASE_URL = "https://ctel-csdp-worker.thanhlm120797.workers.dev"
DEFAULT_TZ = "Asia/Ho_Chi_Minh"
MANAGEMENT_CHAT_PURPOSE = "management"
OPS_CHAT_PURPOSE = "ops"
APPROVAL_CHAT_PURPOSE = "approvals"

[triggers]
crons = ["0 1 * * *", "30 1 * * 1", "0 */2 * * *"]
