-- Auto-generated replacement seed based on uploaded hypothetical source list
PRAGMA foreign_keys = OFF;
DELETE FROM audit_events;
DELETE FROM comments;
DELETE FROM health_snapshots;
DELETE FROM approvals;
DELETE FROM deliverables;
DELETE FROM blockers;
DELETE FROM risks;
DELETE FROM tasks;
DELETE FROM project_members;
DELETE FROM projects;
DELETE FROM telegram_chats;
DELETE FROM users;
DELETE FROM sqlite_sequence WHERE name IN ('users','telegram_chats','projects','project_members','tasks','risks','blockers','deliverables','approvals','health_snapshots','comments','audit_events');
PRAGMA foreign_keys = ON;

INSERT INTO users (email, display_name, telegram_user_id, telegram_username, role, department) VALUES
('phuc.nguyen@ctel.vn', 'Phúc', '20001', 'phuc_nguyen', 'sa', 'Cyber Solution Architect'),
('thanh.le@ctel.vn', 'Thanh', '20002', 'thanh_le', 'sa', 'Cyber Solution Architect'),
('tuan.tran@ctel.vn', 'Tuấn', '20003', 'tuan_tran', 'sa', 'Cyber Solution Architect'),
('phu.pham@ctel.vn', 'Phú', '20004', 'phu_pham', 'sa', 'Cyber Solution Architect'),
('an.vo@ctel.vn', 'An', '20005', 'an_vo', 'approver', 'Cyber Solution Architect');

INSERT INTO telegram_chats (telegram_chat_id, title, type, purpose) VALUES
('-100111', 'CTEL SA Cyber Ops', 'group', 'ops'),
('-100112', 'CTEL SA Cyber Approvals', 'group', 'approvals'),
('-100113', 'CTEL SA Cyber Management', 'group', 'management');

INSERT INTO projects (code, name, customer_name, service_line, type, status, priority, stage, owner_user_id, requester_user_id, sponsor_user_id, health_score, health_status, health_reason, start_date, due_date, description, tags_json) VALUES
('CTEL-SA-2026-001','Dịch vụ Tư vấn ATTT mạng','Công ty TNHH Dược phẩm và Trang thiết bị Y tế Hoàng Đức','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-01','2026-04-01','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty TNHH Dược phẩm và Trang thiết bị Y tế Hoàng Đức','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-002','Đánh giá, Kiểm thử bảo mật','Công ty TNHH Edu Link Việt Nam','security_solution','review','won','medium','closed',2,3,5,92,'on_track','Opportunity won / closed successfully.','2026-03-02','2026-04-02','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty TNHH Edu Link Việt Nam','["WIN","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-003','Security','Công ty TNHH Giải pháp Công nghệ Easy AI','security_solution','presales','lost','low','closed',3,4,5,25,'blocked','Marked as lost opportunity.','2026-03-03','2026-04-03','Security cho khách hàng Công ty TNHH Giải pháp Công nghệ Easy AI','["LOST","Security"]'),
('CTEL-SA-2026-004','Đánh giá, Kiểm thử bảo mật','Ngân hàng Bank Of Communications Co., Ltd - Chi nhánh Thành Phố Hồ Chí Minh','security_solution','review','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-04','2026-04-04','Đánh giá, Kiểm thử bảo mật cho khách hàng Ngân hàng Bank Of Communications Co., Ltd - Chi nhánh Thành Phố Hồ Chí Minh','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-005','Dịch vụ vận hành giải pháp ATTT','Trung tâm Thông tin tín dụng Quốc gia Việt Nam','security_solution','delivery','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-05','2026-04-05','Dịch vụ vận hành giải pháp ATTT cho khách hàng Trung tâm Thông tin tín dụng Quốc gia Việt Nam','["PROCESSING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-006','License EDR','Trung tâm Thông tin tín dụng Quốc gia Việt Nam','security_solution','delivery','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-06','2026-04-06','License EDR cho khách hàng Trung tâm Thông tin tín dụng Quốc gia Việt Nam','["PROCESSING","License EDR"]'),
('CTEL-SA-2026-007','Security','Công ty TNHH CJ CGV Việt Nam','security_solution','presales','won','medium','closed',2,3,5,92,'on_track','Opportunity won / closed successfully.','2026-03-07','2026-04-07','Security cho khách hàng Công ty TNHH CJ CGV Việt Nam','["WIN","Security"]'),
('CTEL-SA-2026-008','Cloud WAAP','Công ty TNHH HQSOFT','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-08','2026-04-08','Cloud WAAP cho khách hàng Công ty TNHH HQSOFT','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-009','Cloud WAAP','Tổng công ty Thương mại Sài Gòn - TNHH Một thành viên','security_solution','presales','won','medium','closed',4,5,5,92,'on_track','Opportunity won / closed successfully.','2026-03-09','2026-04-09','Cloud WAAP cho khách hàng Tổng công ty Thương mại Sài Gòn - TNHH Một thành viên','["WIN","Cloud WAAP"]'),
('CTEL-SA-2026-010','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Bluecore','security_solution','review','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-10','2026-04-10','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Bluecore','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-011','Dịch vụ Tư vấn ATTT mạng','Công ty Cổ phần Đầu tư Thương mại Phát triển Nhất Tín','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-11','2026-04-11','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty Cổ phần Đầu tư Thương mại Phát triển Nhất Tín','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-012','Dịch vụ Tư vấn ATTT mạng','Công ty Cổ phần Dược phẩm Pharmacity','security_solution','presales','pending','medium','intake',2,3,5,82,'at_risk','Pending qualification or waiting for next action.','2026-03-12','2026-04-12','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty Cổ phần Dược phẩm Pharmacity','["PENDING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-013','Dịch vụ triển khai giải pháp ATTT','Công ty Cổ phần Vietful','security_solution','delivery','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-13','2026-04-13','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty Cổ phần Vietful','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-014','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Vietful','security_solution','review','lost','low','closed',4,5,5,25,'blocked','Marked as lost opportunity.','2026-03-14','2026-04-14','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Vietful','["LOST","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-015','Security','Công ty Cổ phần Giải pháp Hệ thống Long Vân','security_solution','presales','cancelled','low','closed',5,1,5,15,'blocked','Cancelled and closed.','2026-03-15','2026-04-15','Security cho khách hàng Công ty Cổ phần Giải pháp Hệ thống Long Vân','["CANCEL","Security"]'),
('CTEL-SA-2026-016','Đánh giá, Kiểm thử bảo mật','Công ty TNHH Kootoro Việt Nam','security_solution','review','pending','medium','intake',1,2,5,82,'at_risk','Pending qualification or waiting for next action.','2026-03-16','2026-04-16','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty TNHH Kootoro Việt Nam','["PENDING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-017','Dịch vụ Tư vấn ATTT mạng','Tổng công ty Hàng không Việt Nam','security_solution','presales','cancelled','low','closed',2,3,5,15,'blocked','Cancelled and closed.','2026-03-17','2026-04-17','Dịch vụ Tư vấn ATTT mạng cho khách hàng Tổng công ty Hàng không Việt Nam','["CANCEL","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-018','Cloud WAAP','Công ty Cổ phần Eplus Research','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-18','2026-04-18','Cloud WAAP cho khách hàng Công ty Cổ phần Eplus Research','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-019','Dịch vụ triển khai giải pháp ATTT','Công ty Cổ phần Dịch vụ Tư vấn Rapbank Việt Nam','security_solution','delivery','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-19','2026-04-19','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty Cổ phần Dịch vụ Tư vấn Rapbank Việt Nam','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-020','Dịch vụ Tư vấn ATTT mạng','CÔNG TY CỔ PHẦN SANAN','security_solution','presales','pending','medium','intake',5,1,5,82,'at_risk','Pending qualification or waiting for next action.','2026-03-20','2026-04-20','Dịch vụ Tư vấn ATTT mạng cho khách hàng CÔNG TY CỔ PHẦN SANAN','["PENDING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-021','Đánh giá, Kiểm thử bảo mật','Công ty Điện tử Meiko Hải Dương Việt Nam','security_solution','review','cancelled','low','closed',1,2,5,15,'blocked','Cancelled and closed.','2026-03-21','2026-04-21','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Điện tử Meiko Hải Dương Việt Nam','["CANCEL","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-022','Cloud WAAP','Tổng Công ty Máy động lực và Máy nông nghiệp Việt Nam - CTCP','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-22','2026-04-22','Cloud WAAP cho khách hàng Tổng Công ty Máy động lực và Máy nông nghiệp Việt Nam - CTCP','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-023','CDN/MultiCDN','Công ty Cổ phần Tập đoàn Meey Land','security_solution','presales','won','medium','closed',3,4,5,92,'on_track','Opportunity won / closed successfully.','2026-03-23','2026-04-23','CDN/MultiCDN cho khách hàng Công ty Cổ phần Tập đoàn Meey Land','["WIN","CDN/MultiCDN"]'),
('CTEL-SA-2026-024','Dịch vụ Tư vấn ATTT mạng','Công ty TNHH CJ Olivenetworks Vina','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-24','2026-04-24','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty TNHH CJ Olivenetworks Vina','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-025','CDN/MultiCDN','Công ty Cổ phần Vinsmart Future','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-25','2026-04-25','CDN/MultiCDN cho khách hàng Công ty Cổ phần Vinsmart Future','["PROCESSING","CDN/MultiCDN"]'),
('CTEL-SA-2026-026','Security hoa hồng chia sẻ','Công ty TNHH An ninh An toàn Thông tin CMC','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-26','2026-04-26','Security hoa hồng chia sẻ cho khách hàng Công ty TNHH An ninh An toàn Thông tin CMC','["PROCESSING","Security hoa hồng chia sẻ"]'),
('CTEL-SA-2026-027','Security hoa hồng chia sẻ','Công ty TNHH An ninh An toàn Thông tin CMC','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-27','2026-04-27','Security hoa hồng chia sẻ cho khách hàng Công ty TNHH An ninh An toàn Thông tin CMC','["PROCESSING","Security hoa hồng chia sẻ"]'),
('CTEL-SA-2026-028','Security hoa hồng chia sẻ','Công ty TNHH An ninh An toàn Thông tin CMC','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-28','2026-04-28','Security hoa hồng chia sẻ cho khách hàng Công ty TNHH An ninh An toàn Thông tin CMC','["PROCESSING","Security hoa hồng chia sẻ"]'),
('CTEL-SA-2026-029','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Công nghệ Isofh','security_solution','review','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-01','2026-04-01','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Công nghệ Isofh','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-030','Dịch vụ triển khai giải pháp ATTT','Công ty Cổ phần Công nghệ Isofh','security_solution','delivery','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-02','2026-04-02','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty Cổ phần Công nghệ Isofh','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-031','CDN/MultiCDN','Công ty TNHH Viettel - CHT','security_solution','presales','cancelled','low','closed',1,2,5,15,'blocked','Cancelled and closed.','2026-03-03','2026-04-03','CDN/MultiCDN cho khách hàng Công ty TNHH Viettel - CHT','["CANCEL","CDN/MultiCDN"]'),
('CTEL-SA-2026-032','Security hoa hồng chia sẻ','Công ty Cổ phần Be Group','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-04','2026-04-04','Security hoa hồng chia sẻ cho khách hàng Công ty Cổ phần Be Group','["PROCESSING","Security hoa hồng chia sẻ"]'),
('CTEL-SA-2026-033','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Giải pháp Công nghệ Medx','security_solution','review','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-05','2026-04-05','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Giải pháp Công nghệ Medx','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-034','License DLP','Trung tâm Hỗ trợ Đấu thầu','security_solution','delivery','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-06','2026-04-06','License DLP cho khách hàng Trung tâm Hỗ trợ Đấu thầu','["PROCESSING","License DLP"]'),
('CTEL-SA-2026-035','License ZTNA','Trung tâm Hỗ trợ Đấu thầu','security_solution','delivery','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-07','2026-04-07','License ZTNA cho khách hàng Trung tâm Hỗ trợ Đấu thầu','["PROCESSING","License ZTNA"]'),
('CTEL-SA-2026-036','Dịch vụ Tư vấn ATTT mạng','Công ty TNHH NTT Data Việt Nam Solutions','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-08','2026-04-08','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty TNHH NTT Data Việt Nam Solutions','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-037','Cloud WAAP','Unloq International Company Limited','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-09','2026-04-09','Cloud WAAP cho khách hàng Unloq International Company Limited','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-038','Cloud WAAP','Công ty TNHH Sinovnl','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-10','2026-04-10','Cloud WAAP cho khách hàng Công ty TNHH Sinovnl','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-039','Security','Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','security_solution','presales','cancelled','low','closed',4,5,5,15,'blocked','Cancelled and closed.','2026-03-11','2026-04-11','Security cho khách hàng Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','["CANCEL","Security"]'),
('CTEL-SA-2026-040','CDN/MultiCDN','Công ty TNHH Thu phí Tự động VETC','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-12','2026-04-12','CDN/MultiCDN cho khách hàng Công ty TNHH Thu phí Tự động VETC','["PROCESSING","CDN/MultiCDN"]'),
('CTEL-SA-2026-041','Dịch vụ vận hành giải pháp ATTT','Tổng Công Ty Đầu Tư Phát Triển Đường Cao Tốc Việt Nam - Công Ty TNHH Một Thành Viên','security_solution','delivery','pending','medium','intake',1,2,5,82,'at_risk','Pending qualification or waiting for next action.','2026-03-13','2026-04-13','Dịch vụ vận hành giải pháp ATTT cho khách hàng Tổng Công Ty Đầu Tư Phát Triển Đường Cao Tốc Việt Nam - Công Ty TNHH Một Thành Viên','["PENDING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-042','Đánh giá, Kiểm thử bảo mật','Trung tâm Quản lý Luồng không lưu - Chi nhánh Tổng công ty Quản lý bay Việt Nam - Công ty TNHH','security_solution','review','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-14','2026-04-14','Đánh giá, Kiểm thử bảo mật cho khách hàng Trung tâm Quản lý Luồng không lưu - Chi nhánh Tổng công ty Quản lý bay Việt Nam - Công ty TNHH','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-043','CDN/MultiCDN','Công ty Cổ phần Công nghệ Giáo dục Thông minh','security_solution','presales','cancelled','low','closed',3,4,5,15,'blocked','Cancelled and closed.','2026-03-15','2026-04-15','CDN/MultiCDN cho khách hàng Công ty Cổ phần Công nghệ Giáo dục Thông minh','["CANCEL","CDN/MultiCDN"]'),
('CTEL-SA-2026-044','Cloud WAAP','Công ty Cổ phần Vĩnh Quang','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-16','2026-04-16','Cloud WAAP cho khách hàng Công ty Cổ phần Vĩnh Quang','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-045','CDN/MultiCDN','Công ty Cổ phần Công nghệ Sapo','security_solution','presales','cancelled','low','closed',5,1,5,15,'blocked','Cancelled and closed.','2026-03-17','2026-04-17','CDN/MultiCDN cho khách hàng Công ty Cổ phần Công nghệ Sapo','["CANCEL","CDN/MultiCDN"]'),
('CTEL-SA-2026-046','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Cấp nước Thủ Đức','security_solution','review','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-18','2026-04-18','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Cấp nước Thủ Đức','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-047','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Công nghệ KiotViet','security_solution','review','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-19','2026-04-19','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Công nghệ KiotViet','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-048','Đánh giá, Kiểm thử bảo mật','Chi nhánh Han - Công ty Cổ phần Công nghệ Du lịch Gotadi','security_solution','review','cancelled','low','closed',3,4,5,15,'blocked','Cancelled and closed.','2026-03-20','2026-04-20','Đánh giá, Kiểm thử bảo mật cho khách hàng Chi nhánh Han - Công ty Cổ phần Công nghệ Du lịch Gotadi','["CANCEL","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-049','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Công nghệ - Viễn thông Elcom','security_solution','review','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-21','2026-04-21','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Công nghệ - Viễn thông Elcom','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-050','Dịch vụ Tư vấn ATTT mạng','Công ty Cổ phần Fiingroup Việt Nam','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-22','2026-04-22','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty Cổ phần Fiingroup Việt Nam','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-051','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Alinacom','security_solution','review','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-23','2026-04-23','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Alinacom','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-052','Security','Công ty Cổ phần Giải pháp Hệ thống Long Vân','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-24','2026-04-24','Security cho khách hàng Công ty Cổ phần Giải pháp Hệ thống Long Vân','["PROCESSING","Security"]'),
('CTEL-SA-2026-053','Dịch vụ Tư vấn ATTT mạng','Trung tâm Dịch vụ Chuyển đổi số-Chi nhánh Tổng Công ty Công nghệ-Viễn thông Toàn cầu','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-25','2026-04-25','Dịch vụ Tư vấn ATTT mạng cho khách hàng Trung tâm Dịch vụ Chuyển đổi số-Chi nhánh Tổng Công ty Công nghệ-Viễn thông Toàn cầu','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-054','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần chuỗi Thực phẩm TH','security_solution','review','lost','low','closed',4,5,5,25,'blocked','Marked as lost opportunity.','2026-03-26','2026-04-26','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần chuỗi Thực phẩm TH','["LOST","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-055','Security','Công ty TNHH Trung tâm Dữ liệu số DC','security_solution','presales','cancelled','low','closed',5,1,5,15,'blocked','Cancelled and closed.','2026-03-27','2026-04-27','Security cho khách hàng Công ty TNHH Trung tâm Dữ liệu số DC','["CANCEL","Security"]'),
('CTEL-SA-2026-056','Security','Cục Công Nghệ Thông Tin Bộ Tư Pháp','security_solution','presales','cancelled','low','closed',1,2,5,15,'blocked','Cancelled and closed.','2026-03-28','2026-04-28','Security cho khách hàng Cục Công Nghệ Thông Tin Bộ Tư Pháp','["CANCEL","Security"]'),
('CTEL-SA-2026-057','Đánh giá, Kiểm thử bảo mật','Công ty TNHH CMC Global','security_solution','review','cancelled','low','closed',2,3,5,15,'blocked','Cancelled and closed.','2026-03-01','2026-04-01','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty TNHH CMC Global','["CANCEL","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-058','Cloud WAAP','Công ty TNHH NTT Data Việt Nam Solutions','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-02','2026-04-02','Cloud WAAP cho khách hàng Công ty TNHH NTT Data Việt Nam Solutions','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-059','CDN/MultiCDN','Công ty Cổ phần Orotech','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-03','2026-04-03','CDN/MultiCDN cho khách hàng Công ty Cổ phần Orotech','["PROCESSING","CDN/MultiCDN"]'),
('CTEL-SA-2026-060','Cloud WAAP','Công ty Cổ phần Orotech','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-04','2026-04-04','Cloud WAAP cho khách hàng Công ty Cổ phần Orotech','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-061','Security','Công ty Cổ phần Orotech','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-05','2026-04-05','Security cho khách hàng Công ty Cổ phần Orotech','["PROCESSING","Security"]'),
('CTEL-SA-2026-062','Security','Trung tâm Chứng thực Điện tử Quốc gia','security_solution','presales','cancelled','low','closed',2,3,5,15,'blocked','Cancelled and closed.','2026-03-06','2026-04-06','Security cho khách hàng Trung tâm Chứng thực Điện tử Quốc gia','["CANCEL","Security"]'),
('CTEL-SA-2026-063','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Đầu tư Kỹ thuật và Thương mại Thành Long','security_solution','review','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-07','2026-04-07','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Đầu tư Kỹ thuật và Thương mại Thành Long','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-064','Đánh giá, Kiểm thử bảo mật','Công ty TNHH Nature Story','security_solution','review','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-08','2026-04-08','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty TNHH Nature Story','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-065','Dịch vụ triển khai giải pháp ATTT','Công ty Cổ phần Tập đoàn Karofi','security_solution','delivery','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-09','2026-04-09','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty Cổ phần Tập đoàn Karofi','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-066','License SIEM','Công ty TNHH De Heus','security_solution','delivery','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-10','2026-04-10','License SIEM cho khách hàng Công ty TNHH De Heus','["PROCESSING","License SIEM"]'),
('CTEL-SA-2026-067','CDN/MultiCDN','Công ty TNHH Thương mại Dịch vụ Vexere','security_solution','presales','pending','medium','intake',2,3,5,82,'at_risk','Pending qualification or waiting for next action.','2026-03-11','2026-04-11','CDN/MultiCDN cho khách hàng Công ty TNHH Thương mại Dịch vụ Vexere','["PENDING","CDN/MultiCDN"]'),
('CTEL-SA-2026-068','CDN/MultiCDN','Báo công thương','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-12','2026-04-12','CDN/MultiCDN cho khách hàng Báo công thương','["PROCESSING","CDN/MultiCDN"]'),
('CTEL-SA-2026-069','Cloud WAAP','Báo công thương','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-13','2026-04-13','Cloud WAAP cho khách hàng Báo công thương','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-070','Security','Báo công thương','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-14','2026-04-14','Security cho khách hàng Báo công thương','["PROCESSING","Security"]'),
('CTEL-SA-2026-071','Security','Công ty TNHH Quản lý Quỹ Bảo Việt','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-15','2026-04-15','Security cho khách hàng Công ty TNHH Quản lý Quỹ Bảo Việt','["PROCESSING","Security"]'),
('CTEL-SA-2026-072','CDN/MultiCDN','Công ty Cổ phần Công nghệ Sapo','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-16','2026-04-16','CDN/MultiCDN cho khách hàng Công ty Cổ phần Công nghệ Sapo','["PROCESSING","CDN/MultiCDN"]'),
('CTEL-SA-2026-073','Đánh giá, Kiểm thử bảo mật','Net Protections','security_solution','review','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-17','2026-04-17','Đánh giá, Kiểm thử bảo mật cho khách hàng Net Protections','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-074','License NDR','Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Việt Nam','security_solution','delivery','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-18','2026-04-18','License NDR cho khách hàng Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Việt Nam','["PROCESSING","License NDR"]'),
('CTEL-SA-2026-075','Dịch vụ Tư vấn ATTT mạng','Công ty TNHH Tổng Công ty Công nghệ và Giải pháp CMC','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-19','2026-04-19','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty TNHH Tổng Công ty Công nghệ và Giải pháp CMC','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-076','CDN/MultiCDN','Công ty Cổ phần Funtap','security_solution','presales','pending','medium','intake',1,2,5,82,'at_risk','Pending qualification or waiting for next action.','2026-03-20','2026-04-20','CDN/MultiCDN cho khách hàng Công ty Cổ phần Funtap','["PENDING","CDN/MultiCDN"]'),
('CTEL-SA-2026-077','License DLP','Công ty Cổ phần Insmart','security_solution','delivery','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-21','2026-04-21','License DLP cho khách hàng Công ty Cổ phần Insmart','["PROCESSING","License DLP"]'),
('CTEL-SA-2026-078','Dịch vụ Tư vấn ATTT mạng','Công ty TNHH Điểm Sáng Công nghệ Investidea','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-22','2026-04-22','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty TNHH Điểm Sáng Công nghệ Investidea','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-079','Dịch vụ Tư vấn ATTT mạng','Công ty Cổ phần VIEON','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-23','2026-04-23','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty Cổ phần VIEON','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-080','Security','Công ty Cổ phần THS Game','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-24','2026-04-24','Security cho khách hàng Công ty Cổ phần THS Game','["PROCESSING","Security"]'),
('CTEL-SA-2026-081','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Sàn giao dịch Tài sản Mã hóa Lộc Phát Việt Nam','security_solution','review','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-25','2026-04-25','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Sàn giao dịch Tài sản Mã hóa Lộc Phát Việt Nam','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-082','Security','Chi nhánh Trung tâm Công nghệ Thông tin Tập đoàn Bảo Việt','security_solution','presales','won','medium','closed',2,3,5,92,'on_track','Opportunity won / closed successfully.','2026-03-26','2026-04-26','Security cho khách hàng Chi nhánh Trung tâm Công nghệ Thông tin Tập đoàn Bảo Việt','["WIN","Security"]'),
('CTEL-SA-2026-083','Cloud WAAP','Công ty Cổ phần Đầu tư Xây dựng và Kỹ thuật VNCN E&C','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-27','2026-04-27','Cloud WAAP cho khách hàng Công ty Cổ phần Đầu tư Xây dựng và Kỹ thuật VNCN E&C','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-084','License DLP','Công ty TNHH Agent-X','security_solution','delivery','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-28','2026-04-28','License DLP cho khách hàng Công ty TNHH Agent-X','["PROCESSING","License DLP"]'),
('CTEL-SA-2026-085','Đánh giá, Kiểm thử bảo mật','Công ty Trách nhiệm hữu hạn Dự án Hồ Tràm','security_solution','review','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-01','2026-04-01','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Trách nhiệm hữu hạn Dự án Hồ Tràm','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-086','Dịch vụ triển khai giải pháp ATTT','Công ty Cổ phần Chứng khoán KIS Việt Nam','security_solution','delivery','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-02','2026-04-02','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty Cổ phần Chứng khoán KIS Việt Nam','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-087','Dịch vụ vận hành giải pháp ATTT','Công ty Cổ phần Chứng khoán KIS Việt Nam','security_solution','delivery','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-03','2026-04-03','Dịch vụ vận hành giải pháp ATTT cho khách hàng Công ty Cổ phần Chứng khoán KIS Việt Nam','["PROCESSING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-088','License SIEM','Công ty Cổ phần Chứng khoán KIS Việt Nam','security_solution','delivery','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-04','2026-04-04','License SIEM cho khách hàng Công ty Cổ phần Chứng khoán KIS Việt Nam','["PROCESSING","License SIEM"]'),
('CTEL-SA-2026-089','Dịch vụ Tư vấn ATTT mạng','Công ty Cổ phần CMC OpenAI','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-05','2026-04-05','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty Cổ phần CMC OpenAI','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-090','Đánh giá, Kiểm thử bảo mật','Công ty TNHH Nidec Việt Nam Corporation','security_solution','review','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-06','2026-04-06','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty TNHH Nidec Việt Nam Corporation','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-091','Dịch vụ triển khai giải pháp ATTT','Công ty TNHH Nha khoa Kim','security_solution','delivery','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-07','2026-04-07','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty TNHH Nha khoa Kim','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-092','Security hoa hồng chia sẻ','Công ty TNHH An ninh An toàn Thông tin CMC','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-08','2026-04-08','Security hoa hồng chia sẻ cho khách hàng Công ty TNHH An ninh An toàn Thông tin CMC','["PROCESSING","Security hoa hồng chia sẻ"]'),
('CTEL-SA-2026-093','Security','Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-09','2026-04-09','Security cho khách hàng Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','["PROCESSING","Security"]'),
('CTEL-SA-2026-094','Dịch vụ triển khai giải pháp ATTT','Công ty Cổ phần Giải pháp số Mobifone','security_solution','delivery','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-10','2026-04-10','Dịch vụ triển khai giải pháp ATTT cho khách hàng Công ty Cổ phần Giải pháp số Mobifone','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-095','Dịch vụ Tư vấn ATTT mạng','Tổng công ty Cổ phần Bảo hiểm Petrolimex','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-11','2026-04-11','Dịch vụ Tư vấn ATTT mạng cho khách hàng Tổng công ty Cổ phần Bảo hiểm Petrolimex','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-096','Dịch vụ vận hành giải pháp ATTT','Công ty TNHH Samsung SDS Việt Nam','security_solution','delivery','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-12','2026-04-12','Dịch vụ vận hành giải pháp ATTT cho khách hàng Công ty TNHH Samsung SDS Việt Nam','["PROCESSING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-097','Cloud WAAP','Công Ty Cổ Phần Công Nghệ Kỹ Thuật Số - Hitd','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-13','2026-04-13','Cloud WAAP cho khách hàng Công Ty Cổ Phần Công Nghệ Kỹ Thuật Số - Hitd','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-098','Cloud WAAP','Công Ty Cổ Phần Tiên Phong Invest','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-14','2026-04-14','Cloud WAAP cho khách hàng Công Ty Cổ Phần Tiên Phong Invest','["PROCESSING","Cloud WAAP"]'),
('CTEL-SA-2026-099','Security','Công Ty Cổ Phần Tiên Phong Invest','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-15','2026-04-15','Security cho khách hàng Công Ty Cổ Phần Tiên Phong Invest','["PROCESSING","Security"]'),
('CTEL-SA-2026-100','Đánh giá, Kiểm thử bảo mật','Tổng công ty Bưu điện Việt Nam','security_solution','review','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-16','2026-04-16','Đánh giá, Kiểm thử bảo mật cho khách hàng Tổng công ty Bưu điện Việt Nam','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-101','Dịch vụ Tư vấn ATTT mạng','Công Ty Cổ Phần Công Nghệ Nền Tảng Số Dtals','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-17','2026-04-17','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công Ty Cổ Phần Công Nghệ Nền Tảng Số Dtals','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-102','Dịch vụ vận hành giải pháp ATTT','Công ty TNHH CMC Global','security_solution','delivery','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-18','2026-04-18','Dịch vụ vận hành giải pháp ATTT cho khách hàng Công ty TNHH CMC Global','["PROCESSING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-103','Dịch vụ Tư vấn ATTT mạng','Công Ty Cổ Phần Pah Technology Việt Nam','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-19','2026-04-19','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công Ty Cổ Phần Pah Technology Việt Nam','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-104','Dịch vụ vận hành giải pháp ATTT','Ngân hàng Thương mại Cổ phần Kiên Long','security_solution','delivery','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-20','2026-04-20','Dịch vụ vận hành giải pháp ATTT cho khách hàng Ngân hàng Thương mại Cổ phần Kiên Long','["PROCESSING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-105','Dịch vụ triển khai giải pháp ATTT','Ngân hàng Thương mại Cổ phần Kiên Long','security_solution','delivery','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-21','2026-04-21','Dịch vụ triển khai giải pháp ATTT cho khách hàng Ngân hàng Thương mại Cổ phần Kiên Long','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-106','Dịch vụ triển khai giải pháp ATTT','Ngân hàng Thương mại Cổ phần Thịnh Vượng và Phát triển','security_solution','delivery','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-22','2026-04-22','Dịch vụ triển khai giải pháp ATTT cho khách hàng Ngân hàng Thương mại Cổ phần Thịnh Vượng và Phát triển','["PROCESSING","Dịch vụ triển khai giải pháp ATTT"]'),
('CTEL-SA-2026-107','Dịch vụ Tư vấn ATTT mạng','Chương trình phát triển liên hiệp quốc (UNDP)','security_solution','presales','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-23','2026-04-23','Dịch vụ Tư vấn ATTT mạng cho khách hàng Chương trình phát triển liên hiệp quốc (UNDP)','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-108','Dịch vụ Tư vấn ATTT mạng','Cảng vụ Hàng không Miền Trung','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-24','2026-04-24','Dịch vụ Tư vấn ATTT mạng cho khách hàng Cảng vụ Hàng không Miền Trung','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-109','Đánh giá, Kiểm thử bảo mật','Công ty Cổ phần Dịch vụ Giải pháp Dữ liệu Trực tuyến Việt Nam','security_solution','review','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-25','2026-04-25','Đánh giá, Kiểm thử bảo mật cho khách hàng Công ty Cổ phần Dịch vụ Giải pháp Dữ liệu Trực tuyến Việt Nam','["PROCESSING","Đánh giá, Kiểm thử bảo mật"]'),
('CTEL-SA-2026-110','Dịch vụ Tư vấn ATTT mạng','Công ty TNHH Chứng Khoán Ngân hàng Thương mại cổ phần Ngoại thương Việt Nam','security_solution','presales','active','high','execution',5,1,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-26','2026-04-26','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty TNHH Chứng Khoán Ngân hàng Thương mại cổ phần Ngoại thương Việt Nam','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-111','Dịch vụ Tư vấn ATTT mạng','Công ty Cổ phần Công nghệ Onelink Việt Nam','security_solution','presales','active','high','execution',1,2,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-27','2026-04-27','Dịch vụ Tư vấn ATTT mạng cho khách hàng Công ty Cổ phần Công nghệ Onelink Việt Nam','["PROCESSING","Dịch vụ Tư vấn ATTT mạng"]'),
('CTEL-SA-2026-112','Dịch vụ vận hành giải pháp ATTT','Cục Công nghệ thông tin và Chuyển đổi số','security_solution','delivery','active','high','execution',2,3,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-28','2026-04-28','Dịch vụ vận hành giải pháp ATTT cho khách hàng Cục Công nghệ thông tin và Chuyển đổi số','["PROCESSING","Dịch vụ vận hành giải pháp ATTT"]'),
('CTEL-SA-2026-113','CDN/MultiCDN','Công ty Cổ phần Vinschool','security_solution','presales','active','high','execution',3,4,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-01','2026-04-01','CDN/MultiCDN cho khách hàng Công ty Cổ phần Vinschool','["PROCESSING","CDN/MultiCDN"]'),
('CTEL-SA-2026-114','Security','Công ty TNHH Xylentis','security_solution','presales','active','high','execution',4,5,5,76,'at_risk','Active pipeline item under execution / pursuit.','2026-03-02','2026-04-02','Security cho khách hàng Công ty TNHH Xylentis','["PROCESSING","Security"]');

INSERT INTO project_members (project_id, user_id, member_role) VALUES
(1,1,'owner'),
(1,5,'approver'),
(2,2,'owner'),
(2,5,'approver'),
(3,3,'owner'),
(3,5,'approver'),
(4,4,'owner'),
(4,5,'approver'),
(5,5,'owner'),
(5,5,'approver'),
(6,1,'owner'),
(6,5,'approver'),
(7,2,'owner'),
(7,5,'approver'),
(8,3,'owner'),
(8,5,'approver'),
(9,4,'owner'),
(9,5,'approver'),
(10,5,'owner'),
(10,5,'approver'),
(11,1,'owner'),
(11,5,'approver'),
(12,2,'owner'),
(12,5,'approver'),
(13,3,'owner'),
(13,5,'approver'),
(14,4,'owner'),
(14,5,'approver'),
(15,5,'owner'),
(15,5,'approver'),
(16,1,'owner'),
(16,5,'approver'),
(17,2,'owner'),
(17,5,'approver'),
(18,3,'owner'),
(18,5,'approver'),
(19,4,'owner'),
(19,5,'approver'),
(20,5,'owner'),
(20,5,'approver'),
(21,1,'owner'),
(21,5,'approver'),
(22,2,'owner'),
(22,5,'approver'),
(23,3,'owner'),
(23,5,'approver'),
(24,4,'owner'),
(24,5,'approver'),
(25,5,'owner'),
(25,5,'approver'),
(26,1,'owner'),
(26,5,'approver'),
(27,2,'owner'),
(27,5,'approver'),
(28,3,'owner'),
(28,5,'approver'),
(29,4,'owner'),
(29,5,'approver'),
(30,5,'owner'),
(30,5,'approver'),
(31,1,'owner'),
(31,5,'approver'),
(32,2,'owner'),
(32,5,'approver'),
(33,3,'owner'),
(33,5,'approver'),
(34,4,'owner'),
(34,5,'approver'),
(35,5,'owner'),
(35,5,'approver'),
(36,1,'owner'),
(36,5,'approver'),
(37,2,'owner'),
(37,5,'approver'),
(38,3,'owner'),
(38,5,'approver'),
(39,4,'owner'),
(39,5,'approver'),
(40,5,'owner'),
(40,5,'approver'),
(41,1,'owner'),
(41,5,'approver'),
(42,2,'owner'),
(42,5,'approver'),
(43,3,'owner'),
(43,5,'approver'),
(44,4,'owner'),
(44,5,'approver'),
(45,5,'owner'),
(45,5,'approver'),
(46,1,'owner'),
(46,5,'approver'),
(47,2,'owner'),
(47,5,'approver'),
(48,3,'owner'),
(48,5,'approver'),
(49,4,'owner'),
(49,5,'approver'),
(50,5,'owner'),
(50,5,'approver'),
(51,1,'owner'),
(51,5,'approver'),
(52,2,'owner'),
(52,5,'approver'),
(53,3,'owner'),
(53,5,'approver'),
(54,4,'owner'),
(54,5,'approver'),
(55,5,'owner'),
(55,5,'approver'),
(56,1,'owner'),
(56,5,'approver'),
(57,2,'owner'),
(57,5,'approver'),
(58,3,'owner'),
(58,5,'approver'),
(59,4,'owner'),
(59,5,'approver'),
(60,5,'owner'),
(60,5,'approver'),
(61,1,'owner'),
(61,5,'approver'),
(62,2,'owner'),
(62,5,'approver'),
(63,3,'owner'),
(63,5,'approver'),
(64,4,'owner'),
(64,5,'approver'),
(65,5,'owner'),
(65,5,'approver'),
(66,1,'owner'),
(66,5,'approver'),
(67,2,'owner'),
(67,5,'approver'),
(68,3,'owner'),
(68,5,'approver'),
(69,4,'owner'),
(69,5,'approver'),
(70,5,'owner'),
(70,5,'approver'),
(71,1,'owner'),
(71,5,'approver'),
(72,2,'owner'),
(72,5,'approver'),
(73,3,'owner'),
(73,5,'approver'),
(74,4,'owner'),
(74,5,'approver'),
(75,5,'owner'),
(75,5,'approver'),
(76,1,'owner'),
(76,5,'approver'),
(77,2,'owner'),
(77,5,'approver'),
(78,3,'owner'),
(78,5,'approver'),
(79,4,'owner'),
(79,5,'approver'),
(80,5,'owner'),
(80,5,'approver'),
(81,1,'owner'),
(81,5,'approver'),
(82,2,'owner'),
(82,5,'approver'),
(83,3,'owner'),
(83,5,'approver'),
(84,4,'owner'),
(84,5,'approver'),
(85,5,'owner'),
(85,5,'approver'),
(86,1,'owner'),
(86,5,'approver'),
(87,2,'owner'),
(87,5,'approver'),
(88,3,'owner'),
(88,5,'approver'),
(89,4,'owner'),
(89,5,'approver'),
(90,5,'owner'),
(90,5,'approver'),
(91,1,'owner'),
(91,5,'approver'),
(92,2,'owner'),
(92,5,'approver'),
(93,3,'owner'),
(93,5,'approver'),
(94,4,'owner'),
(94,5,'approver'),
(95,5,'owner'),
(95,5,'approver'),
(96,1,'owner'),
(96,5,'approver'),
(97,2,'owner'),
(97,5,'approver'),
(98,3,'owner'),
(98,5,'approver'),
(99,4,'owner'),
(99,5,'approver'),
(100,5,'owner'),
(100,5,'approver'),
(101,1,'owner'),
(101,5,'approver'),
(102,2,'owner'),
(102,5,'approver'),
(103,3,'owner'),
(103,5,'approver'),
(104,4,'owner'),
(104,5,'approver'),
(105,5,'owner'),
(105,5,'approver'),
(106,1,'owner'),
(106,5,'approver'),
(107,2,'owner'),
(107,5,'approver'),
(108,3,'owner'),
(108,5,'approver'),
(109,4,'owner'),
(109,5,'approver'),
(110,5,'owner'),
(110,5,'approver'),
(111,1,'owner'),
(111,5,'approver'),
(112,2,'owner'),
(112,5,'approver'),
(113,3,'owner'),
(113,5,'approver'),
(114,4,'owner'),
(114,5,'approver');

INSERT INTO tasks (project_id, title, description, bucket, status, priority, category, assignee_user_id, reporter_user_id, due_date, estimate_hours, sequence_no) VALUES
(1,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty TNHH Dược phẩm và Trang thiết bị Y tế Hoàng Đức','in_progress','in_progress','high','general',1,2,'2026-04-01',4,1),
(2,'Chốt hồ sơ thắng thầu / thắng deal','Hoàn tất tài liệu đóng cơ hội cho Công ty TNHH Edu Link Việt Nam','done','completed','medium','closure',2,3,'2026-04-02',2,2),
(3,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty TNHH Giải pháp Công nghệ Easy AI','done','closed','low','closure',3,4,'2026-04-03',1,3),
(4,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Ngân hàng Bank Of Communications Co., Ltd - Chi nhánh Thành Phố Hồ Chí Minh','in_progress','in_progress','high','general',4,5,'2026-04-04',4,4),
(5,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Trung tâm Thông tin tín dụng Quốc gia Việt Nam','in_progress','in_progress','high','general',5,1,'2026-04-05',4,5),
(6,'Triển khai hạng mục chính','License EDR - Trung tâm Thông tin tín dụng Quốc gia Việt Nam','in_progress','in_progress','high','general',1,2,'2026-04-06',4,6),
(7,'Chốt hồ sơ thắng thầu / thắng deal','Hoàn tất tài liệu đóng cơ hội cho Công ty TNHH CJ CGV Việt Nam','done','completed','medium','closure',2,3,'2026-04-07',2,7),
(8,'Follow up khách hàng','Cloud WAAP - Công ty TNHH HQSOFT','in_progress','in_progress','high','general',3,4,'2026-04-08',4,8),
(9,'Chốt hồ sơ thắng thầu / thắng deal','Hoàn tất tài liệu đóng cơ hội cho Tổng công ty Thương mại Sài Gòn - TNHH Một thành viên','done','completed','medium','closure',4,5,'2026-04-09',2,9),
(10,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Bluecore','in_progress','in_progress','high','general',5,1,'2026-04-10',4,10),
(11,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty Cổ phần Đầu tư Thương mại Phát triển Nhất Tín','in_progress','in_progress','high','general',1,2,'2026-04-11',4,11),
(12,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty Cổ phần Dược phẩm Pharmacity','backlog','todo','high','general',2,3,'2026-04-12',4,12),
(13,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty Cổ phần Vietful','in_progress','in_progress','high','general',3,4,'2026-04-13',4,13),
(14,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Cổ phần Vietful','done','closed','low','closure',4,5,'2026-04-14',1,14),
(15,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Cổ phần Giải pháp Hệ thống Long Vân','done','closed','low','closure',5,1,'2026-04-15',1,15),
(16,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty TNHH Kootoro Việt Nam','backlog','todo','high','general',1,2,'2026-04-16',4,16),
(17,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Tổng công ty Hàng không Việt Nam','done','closed','low','closure',2,3,'2026-04-17',1,17),
(18,'Follow up khách hàng','Cloud WAAP - Công ty Cổ phần Eplus Research','in_progress','in_progress','high','general',3,4,'2026-04-18',4,18),
(19,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty Cổ phần Dịch vụ Tư vấn Rapbank Việt Nam','in_progress','in_progress','high','general',4,5,'2026-04-19',4,19),
(20,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - CÔNG TY CỔ PHẦN SANAN','backlog','todo','high','general',5,1,'2026-04-20',4,20),
(21,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Điện tử Meiko Hải Dương Việt Nam','done','closed','low','closure',1,2,'2026-04-21',1,21),
(22,'Follow up khách hàng','Cloud WAAP - Tổng Công ty Máy động lực và Máy nông nghiệp Việt Nam - CTCP','in_progress','in_progress','high','general',2,3,'2026-04-22',4,22),
(23,'Chốt hồ sơ thắng thầu / thắng deal','Hoàn tất tài liệu đóng cơ hội cho Công ty Cổ phần Tập đoàn Meey Land','done','completed','medium','closure',3,4,'2026-04-23',2,23),
(24,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty TNHH CJ Olivenetworks Vina','in_progress','in_progress','high','general',4,5,'2026-04-24',4,24),
(25,'Follow up khách hàng','CDN/MultiCDN - Công ty Cổ phần Vinsmart Future','in_progress','in_progress','high','general',5,1,'2026-04-25',4,25),
(26,'Follow up khách hàng','Security hoa hồng chia sẻ - Công ty TNHH An ninh An toàn Thông tin CMC','in_progress','in_progress','high','general',1,2,'2026-04-26',4,26),
(27,'Follow up khách hàng','Security hoa hồng chia sẻ - Công ty TNHH An ninh An toàn Thông tin CMC','in_progress','in_progress','high','general',2,3,'2026-04-27',4,27),
(28,'Follow up khách hàng','Security hoa hồng chia sẻ - Công ty TNHH An ninh An toàn Thông tin CMC','in_progress','in_progress','high','general',3,4,'2026-04-28',4,28),
(29,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Công nghệ Isofh','in_progress','in_progress','high','general',4,5,'2026-04-01',4,29),
(30,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty Cổ phần Công nghệ Isofh','in_progress','in_progress','high','general',5,1,'2026-04-02',4,30),
(31,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty TNHH Viettel - CHT','done','closed','low','closure',1,2,'2026-04-03',1,31),
(32,'Follow up khách hàng','Security hoa hồng chia sẻ - Công ty Cổ phần Be Group','in_progress','in_progress','high','general',2,3,'2026-04-04',4,32),
(33,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Giải pháp Công nghệ Medx','in_progress','in_progress','high','general',3,4,'2026-04-05',4,33),
(34,'Triển khai hạng mục chính','License DLP - Trung tâm Hỗ trợ Đấu thầu','in_progress','in_progress','high','general',4,5,'2026-04-06',4,34),
(35,'Triển khai hạng mục chính','License ZTNA - Trung tâm Hỗ trợ Đấu thầu','in_progress','in_progress','high','general',5,1,'2026-04-07',4,35),
(36,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty TNHH NTT Data Việt Nam Solutions','in_progress','in_progress','high','general',1,2,'2026-04-08',4,36),
(37,'Follow up khách hàng','Cloud WAAP - Unloq International Company Limited','in_progress','in_progress','high','general',2,3,'2026-04-09',4,37),
(38,'Follow up khách hàng','Cloud WAAP - Công ty TNHH Sinovnl','in_progress','in_progress','high','general',3,4,'2026-04-10',4,38),
(39,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','done','closed','low','closure',4,5,'2026-04-11',1,39),
(40,'Follow up khách hàng','CDN/MultiCDN - Công ty TNHH Thu phí Tự động VETC','in_progress','in_progress','high','general',5,1,'2026-04-12',4,40),
(41,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Tổng Công Ty Đầu Tư Phát Triển Đường Cao Tốc Việt Nam - Công Ty TNHH Một Thành Viên','backlog','todo','high','general',1,2,'2026-04-13',4,41),
(42,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Trung tâm Quản lý Luồng không lưu - Chi nhánh Tổng công ty Quản lý bay Việt Nam - Công ty TNHH','in_progress','in_progress','high','general',2,3,'2026-04-14',4,42),
(43,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Cổ phần Công nghệ Giáo dục Thông minh','done','closed','low','closure',3,4,'2026-04-15',1,43),
(44,'Follow up khách hàng','Cloud WAAP - Công ty Cổ phần Vĩnh Quang','in_progress','in_progress','high','general',4,5,'2026-04-16',4,44),
(45,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Cổ phần Công nghệ Sapo','done','closed','low','closure',5,1,'2026-04-17',1,45),
(46,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Cấp nước Thủ Đức','in_progress','in_progress','high','general',1,2,'2026-04-18',4,46),
(47,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Công nghệ KiotViet','in_progress','in_progress','high','general',2,3,'2026-04-19',4,47),
(48,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Chi nhánh Han - Công ty Cổ phần Công nghệ Du lịch Gotadi','done','closed','low','closure',3,4,'2026-04-20',1,48),
(49,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Công nghệ - Viễn thông Elcom','in_progress','in_progress','high','general',4,5,'2026-04-21',4,49),
(50,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty Cổ phần Fiingroup Việt Nam','in_progress','in_progress','high','general',5,1,'2026-04-22',4,50),
(51,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Alinacom','in_progress','in_progress','high','general',1,2,'2026-04-23',4,51),
(52,'Follow up khách hàng','Security - Công ty Cổ phần Giải pháp Hệ thống Long Vân','in_progress','in_progress','high','general',2,3,'2026-04-24',4,52),
(53,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Trung tâm Dịch vụ Chuyển đổi số-Chi nhánh Tổng Công ty Công nghệ-Viễn thông Toàn cầu','in_progress','in_progress','high','general',3,4,'2026-04-25',4,53),
(54,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty Cổ phần chuỗi Thực phẩm TH','done','closed','low','closure',4,5,'2026-04-26',1,54),
(55,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty TNHH Trung tâm Dữ liệu số DC','done','closed','low','closure',5,1,'2026-04-27',1,55),
(56,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Cục Công Nghệ Thông Tin Bộ Tư Pháp','done','closed','low','closure',1,2,'2026-04-28',1,56),
(57,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Công ty TNHH CMC Global','done','closed','low','closure',2,3,'2026-04-01',1,57),
(58,'Follow up khách hàng','Cloud WAAP - Công ty TNHH NTT Data Việt Nam Solutions','in_progress','in_progress','high','general',3,4,'2026-04-02',4,58),
(59,'Follow up khách hàng','CDN/MultiCDN - Công ty Cổ phần Orotech','in_progress','in_progress','high','general',4,5,'2026-04-03',4,59),
(60,'Follow up khách hàng','Cloud WAAP - Công ty Cổ phần Orotech','in_progress','in_progress','high','general',5,1,'2026-04-04',4,60),
(61,'Follow up khách hàng','Security - Công ty Cổ phần Orotech','in_progress','in_progress','high','general',1,2,'2026-04-05',4,61),
(62,'Lưu hồ sơ đóng cơ hội','Cập nhật lý do đóng cơ hội cho Trung tâm Chứng thực Điện tử Quốc gia','done','closed','low','closure',2,3,'2026-04-06',1,62),
(63,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Đầu tư Kỹ thuật và Thương mại Thành Long','in_progress','in_progress','high','general',3,4,'2026-04-07',4,63),
(64,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty TNHH Nature Story','in_progress','in_progress','high','general',4,5,'2026-04-08',4,64),
(65,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty Cổ phần Tập đoàn Karofi','in_progress','in_progress','high','general',5,1,'2026-04-09',4,65),
(66,'Triển khai hạng mục chính','License SIEM - Công ty TNHH De Heus','in_progress','in_progress','high','general',1,2,'2026-04-10',4,66),
(67,'Follow up khách hàng','CDN/MultiCDN - Công ty TNHH Thương mại Dịch vụ Vexere','backlog','todo','high','general',2,3,'2026-04-11',4,67),
(68,'Follow up khách hàng','CDN/MultiCDN - Báo công thương','in_progress','in_progress','high','general',3,4,'2026-04-12',4,68),
(69,'Follow up khách hàng','Cloud WAAP - Báo công thương','in_progress','in_progress','high','general',4,5,'2026-04-13',4,69),
(70,'Follow up khách hàng','Security - Báo công thương','in_progress','in_progress','high','general',5,1,'2026-04-14',4,70),
(71,'Follow up khách hàng','Security - Công ty TNHH Quản lý Quỹ Bảo Việt','in_progress','in_progress','high','general',1,2,'2026-04-15',4,71),
(72,'Follow up khách hàng','CDN/MultiCDN - Công ty Cổ phần Công nghệ Sapo','in_progress','in_progress','high','general',2,3,'2026-04-16',4,72),
(73,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Net Protections','in_progress','in_progress','high','general',3,4,'2026-04-17',4,73),
(74,'Triển khai hạng mục chính','License NDR - Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Việt Nam','in_progress','in_progress','high','general',4,5,'2026-04-18',4,74),
(75,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty TNHH Tổng Công ty Công nghệ và Giải pháp CMC','in_progress','in_progress','high','general',5,1,'2026-04-19',4,75),
(76,'Follow up khách hàng','CDN/MultiCDN - Công ty Cổ phần Funtap','backlog','todo','high','general',1,2,'2026-04-20',4,76),
(77,'Triển khai hạng mục chính','License DLP - Công ty Cổ phần Insmart','in_progress','in_progress','high','general',2,3,'2026-04-21',4,77),
(78,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty TNHH Điểm Sáng Công nghệ Investidea','in_progress','in_progress','high','general',3,4,'2026-04-22',4,78),
(79,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty Cổ phần VIEON','in_progress','in_progress','high','general',4,5,'2026-04-23',4,79),
(80,'Follow up khách hàng','Security - Công ty Cổ phần THS Game','in_progress','in_progress','high','general',5,1,'2026-04-24',4,80),
(81,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Sàn giao dịch Tài sản Mã hóa Lộc Phát Việt Nam','in_progress','in_progress','high','general',1,2,'2026-04-25',4,81),
(82,'Chốt hồ sơ thắng thầu / thắng deal','Hoàn tất tài liệu đóng cơ hội cho Chi nhánh Trung tâm Công nghệ Thông tin Tập đoàn Bảo Việt','done','completed','medium','closure',2,3,'2026-04-26',2,82),
(83,'Follow up khách hàng','Cloud WAAP - Công ty Cổ phần Đầu tư Xây dựng và Kỹ thuật VNCN E&C','in_progress','in_progress','high','general',3,4,'2026-04-27',4,83),
(84,'Triển khai hạng mục chính','License DLP - Công ty TNHH Agent-X','in_progress','in_progress','high','general',4,5,'2026-04-28',4,84),
(85,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Trách nhiệm hữu hạn Dự án Hồ Tràm','in_progress','in_progress','high','general',5,1,'2026-04-01',4,85),
(86,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty Cổ phần Chứng khoán KIS Việt Nam','in_progress','in_progress','high','general',1,2,'2026-04-02',4,86),
(87,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Công ty Cổ phần Chứng khoán KIS Việt Nam','in_progress','in_progress','high','general',2,3,'2026-04-03',4,87),
(88,'Triển khai hạng mục chính','License SIEM - Công ty Cổ phần Chứng khoán KIS Việt Nam','in_progress','in_progress','high','general',3,4,'2026-04-04',4,88),
(89,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty Cổ phần CMC OpenAI','in_progress','in_progress','high','general',4,5,'2026-04-05',4,89),
(90,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty TNHH Nidec Việt Nam Corporation','in_progress','in_progress','high','general',5,1,'2026-04-06',4,90),
(91,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty TNHH Nha khoa Kim','in_progress','in_progress','high','general',1,2,'2026-04-07',4,91),
(92,'Follow up khách hàng','Security hoa hồng chia sẻ - Công ty TNHH An ninh An toàn Thông tin CMC','in_progress','in_progress','high','general',2,3,'2026-04-08',4,92),
(93,'Follow up khách hàng','Security - Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','in_progress','in_progress','high','general',3,4,'2026-04-09',4,93),
(94,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Công ty Cổ phần Giải pháp số Mobifone','in_progress','in_progress','high','general',4,5,'2026-04-10',4,94),
(95,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Tổng công ty Cổ phần Bảo hiểm Petrolimex','in_progress','in_progress','high','general',5,1,'2026-04-11',4,95),
(96,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Công ty TNHH Samsung SDS Việt Nam','in_progress','in_progress','high','general',1,2,'2026-04-12',4,96),
(97,'Follow up khách hàng','Cloud WAAP - Công Ty Cổ Phần Công Nghệ Kỹ Thuật Số - Hitd','in_progress','in_progress','high','general',2,3,'2026-04-13',4,97),
(98,'Follow up khách hàng','Cloud WAAP - Công Ty Cổ Phần Tiên Phong Invest','in_progress','in_progress','high','general',3,4,'2026-04-14',4,98),
(99,'Follow up khách hàng','Security - Công Ty Cổ Phần Tiên Phong Invest','in_progress','in_progress','high','general',4,5,'2026-04-15',4,99),
(100,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Tổng công ty Bưu điện Việt Nam','in_progress','in_progress','high','general',5,1,'2026-04-16',4,100),
(101,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công Ty Cổ Phần Công Nghệ Nền Tảng Số Dtals','in_progress','in_progress','high','general',1,2,'2026-04-17',4,101),
(102,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Công ty TNHH CMC Global','in_progress','in_progress','high','general',2,3,'2026-04-18',4,102),
(103,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công Ty Cổ Phần Pah Technology Việt Nam','in_progress','in_progress','high','general',3,4,'2026-04-19',4,103),
(104,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Ngân hàng Thương mại Cổ phần Kiên Long','in_progress','in_progress','high','general',4,5,'2026-04-20',4,104),
(105,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Ngân hàng Thương mại Cổ phần Kiên Long','in_progress','in_progress','high','general',5,1,'2026-04-21',4,105),
(106,'Triển khai hạng mục chính','Dịch vụ triển khai giải pháp ATTT - Ngân hàng Thương mại Cổ phần Thịnh Vượng và Phát triển','in_progress','in_progress','high','general',1,2,'2026-04-22',4,106),
(107,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Chương trình phát triển liên hiệp quốc (UNDP)','in_progress','in_progress','high','general',2,3,'2026-04-23',4,107),
(108,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Cảng vụ Hàng không Miền Trung','in_progress','in_progress','high','general',3,4,'2026-04-24',4,108),
(109,'Triển khai hạng mục chính','Đánh giá, Kiểm thử bảo mật - Công ty Cổ phần Dịch vụ Giải pháp Dữ liệu Trực tuyến Việt Nam','in_progress','in_progress','high','general',4,5,'2026-04-25',4,109),
(110,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty TNHH Chứng Khoán Ngân hàng Thương mại cổ phần Ngoại thương Việt Nam','in_progress','in_progress','high','general',5,1,'2026-04-26',4,110),
(111,'Follow up khách hàng','Dịch vụ Tư vấn ATTT mạng - Công ty Cổ phần Công nghệ Onelink Việt Nam','in_progress','in_progress','high','general',1,2,'2026-04-27',4,111),
(112,'Triển khai hạng mục chính','Dịch vụ vận hành giải pháp ATTT - Cục Công nghệ thông tin và Chuyển đổi số','in_progress','in_progress','high','general',2,3,'2026-04-28',4,112),
(113,'Follow up khách hàng','CDN/MultiCDN - Công ty Cổ phần Vinschool','in_progress','in_progress','high','general',3,4,'2026-04-01',4,113),
(114,'Follow up khách hàng','Security - Công ty TNHH Xylentis','in_progress','in_progress','high','general',4,5,'2026-04-02',4,114);

INSERT INTO risks (project_id, title, description, severity, likelihood, risk_score, mitigation_plan, owner_user_id, status, due_date) VALUES
(1,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Dược phẩm và Trang thiết bị Y tế Hoàng Đức','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-01'),
(4,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Ngân hàng Bank Of Communications Co., Ltd - Chi nhánh Thành Phố Hồ Chí Minh','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-04'),
(5,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Trung tâm Thông tin tín dụng Quốc gia Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-05'),
(6,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Trung tâm Thông tin tín dụng Quốc gia Việt Nam','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-06'),
(8,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH HQSOFT','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-08'),
(10,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Bluecore','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-10'),
(11,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Đầu tư Thương mại Phát triển Nhất Tín','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-11'),
(13,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Vietful','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-13'),
(18,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Eplus Research','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-18'),
(19,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Dịch vụ Tư vấn Rapbank Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-19'),
(22,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Tổng Công ty Máy động lực và Máy nông nghiệp Việt Nam - CTCP','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-22'),
(24,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH CJ Olivenetworks Vina','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-24'),
(25,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Vinsmart Future','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-25'),
(26,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH An ninh An toàn Thông tin CMC','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-26'),
(27,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH An ninh An toàn Thông tin CMC','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-27'),
(28,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH An ninh An toàn Thông tin CMC','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-28'),
(29,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Công nghệ Isofh','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-01'),
(30,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Công nghệ Isofh','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-02'),
(32,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Be Group','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-04'),
(33,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Giải pháp Công nghệ Medx','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-05'),
(34,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Trung tâm Hỗ trợ Đấu thầu','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-06'),
(35,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Trung tâm Hỗ trợ Đấu thầu','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-07'),
(36,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH NTT Data Việt Nam Solutions','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-08'),
(37,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Unloq International Company Limited','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-09'),
(38,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Sinovnl','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-10'),
(40,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Thu phí Tự động VETC','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-12'),
(42,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Trung tâm Quản lý Luồng không lưu - Chi nhánh Tổng công ty Quản lý bay Việt Nam - Công ty TNHH','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-14'),
(44,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Vĩnh Quang','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-16'),
(46,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Cấp nước Thủ Đức','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-18'),
(47,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Công nghệ KiotViet','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-19'),
(49,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Công nghệ - Viễn thông Elcom','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-21'),
(50,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Fiingroup Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-22'),
(51,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Alinacom','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-23'),
(52,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Giải pháp Hệ thống Long Vân','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-24'),
(53,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Trung tâm Dịch vụ Chuyển đổi số-Chi nhánh Tổng Công ty Công nghệ-Viễn thông Toàn cầu','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-25'),
(58,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH NTT Data Việt Nam Solutions','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-02'),
(59,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Orotech','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-03'),
(60,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Orotech','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-04'),
(61,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Orotech','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-05'),
(63,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Đầu tư Kỹ thuật và Thương mại Thành Long','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-07'),
(64,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Nature Story','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-08'),
(65,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Tập đoàn Karofi','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-09'),
(66,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH De Heus','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-10'),
(68,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Báo công thương','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-12'),
(69,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Báo công thương','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-13'),
(70,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Báo công thương','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-14'),
(71,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Quản lý Quỹ Bảo Việt','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-15'),
(72,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Công nghệ Sapo','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-16'),
(73,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Net Protections','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-17'),
(74,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-18'),
(75,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Tổng Công ty Công nghệ và Giải pháp CMC','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-19'),
(77,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Insmart','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-21'),
(78,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Điểm Sáng Công nghệ Investidea','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-22'),
(79,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần VIEON','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-23'),
(80,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần THS Game','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-24'),
(81,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Sàn giao dịch Tài sản Mã hóa Lộc Phát Việt Nam','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-25'),
(83,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Đầu tư Xây dựng và Kỹ thuật VNCN E&C','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-27'),
(84,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Agent-X','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-28'),
(85,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Trách nhiệm hữu hạn Dự án Hồ Tràm','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-01'),
(86,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Chứng khoán KIS Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-02'),
(87,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Chứng khoán KIS Việt Nam','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-03'),
(88,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Chứng khoán KIS Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-04'),
(89,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần CMC OpenAI','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-05'),
(90,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Nidec Việt Nam Corporation','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-06'),
(91,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Nha khoa Kim','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-07'),
(92,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH An ninh An toàn Thông tin CMC','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-08'),
(93,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-09'),
(94,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Giải pháp số Mobifone','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-10'),
(95,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Tổng công ty Cổ phần Bảo hiểm Petrolimex','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-11'),
(96,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Samsung SDS Việt Nam','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-12'),
(97,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công Ty Cổ Phần Công Nghệ Kỹ Thuật Số - Hitd','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-13'),
(98,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công Ty Cổ Phần Tiên Phong Invest','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-14'),
(99,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công Ty Cổ Phần Tiên Phong Invest','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-15'),
(100,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Tổng công ty Bưu điện Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-16'),
(101,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công Ty Cổ Phần Công Nghệ Nền Tảng Số Dtals','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-17'),
(102,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH CMC Global','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-18'),
(103,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công Ty Cổ Phần Pah Technology Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-19'),
(104,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Ngân hàng Thương mại Cổ phần Kiên Long','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-20'),
(105,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Ngân hàng Thương mại Cổ phần Kiên Long','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-21'),
(106,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Ngân hàng Thương mại Cổ phần Thịnh Vượng và Phát triển','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-22'),
(107,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Chương trình phát triển liên hiệp quốc (UNDP)','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-23'),
(108,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Cảng vụ Hàng không Miền Trung','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-24'),
(109,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Dịch vụ Giải pháp Dữ liệu Trực tuyến Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-25'),
(110,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Chứng Khoán Ngân hàng Thương mại cổ phần Ngoại thương Việt Nam','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',5,'open','2026-04-26'),
(111,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Công nghệ Onelink Việt Nam','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',1,'open','2026-04-27'),
(112,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Cục Công nghệ thông tin và Chuyển đổi số','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',2,'open','2026-04-28'),
(113,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty Cổ phần Vinschool','medium',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',3,'open','2026-04-01'),
(114,'Theo dõi opportunity / delivery','Cần bám sát tiến độ với Công ty TNHH Xylentis','high',3,9,'Cập nhật khách hàng và nội bộ hằng tuần',4,'open','2026-04-02');

INSERT INTO blockers (project_id, task_id, title, description, owner_user_id, severity, status, due_date, escalation_chat_id) VALUES
(4,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',4,'medium','open','2026-04-04',1),
(8,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',3,'medium','open','2026-04-08',1),
(24,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',4,'medium','open','2026-04-24',1),
(28,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',3,'medium','open','2026-04-28',1),
(32,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',2,'medium','open','2026-04-04',1),
(36,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',1,'medium','open','2026-04-08',1),
(40,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',5,'medium','open','2026-04-12',1),
(44,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',4,'medium','open','2026-04-16',1),
(52,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',2,'medium','open','2026-04-24',1),
(60,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',5,'medium','open','2026-04-04',1),
(64,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',4,'medium','open','2026-04-08',1),
(68,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',3,'medium','open','2026-04-12',1),
(72,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',2,'medium','open','2026-04-16',1),
(80,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',5,'medium','open','2026-04-24',1),
(84,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',4,'medium','open','2026-04-28',1),
(88,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',3,'medium','open','2026-04-04',1),
(92,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',2,'medium','open','2026-04-08',1),
(96,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',1,'medium','open','2026-04-12',1),
(100,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',5,'medium','open','2026-04-16',1),
(104,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',4,'medium','open','2026-04-20',1),
(108,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',3,'medium','open','2026-04-24',1),
(112,NULL,'Chờ phản hồi khách hàng','Khách hàng chưa xác nhận bước tiếp theo',2,'medium','open','2026-04-28',1);

INSERT INTO approvals (project_id, deliverable_id, title, requestor_user_id, approver_user_id, status, expires_at) VALUES
(1,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Dược phẩm và Trang thiết bị Y tế Hoàng Đức',2,5,'pending','2026-04-01 17:00:00'),
(4,NULL,'Phê duyệt phương án / báo giá cho Ngân hàng Bank Of Communications Co., Ltd - Chi nhánh Thành Phố Hồ Chí Minh',5,5,'pending','2026-04-04 17:00:00'),
(5,NULL,'Phê duyệt phương án / báo giá cho Trung tâm Thông tin tín dụng Quốc gia Việt Nam',1,5,'pending','2026-04-05 17:00:00'),
(6,NULL,'Phê duyệt phương án / báo giá cho Trung tâm Thông tin tín dụng Quốc gia Việt Nam',2,5,'pending','2026-04-06 17:00:00'),
(8,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH HQSOFT',4,5,'pending','2026-04-08 17:00:00'),
(10,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Bluecore',1,5,'pending','2026-04-10 17:00:00'),
(11,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Đầu tư Thương mại Phát triển Nhất Tín',2,5,'pending','2026-04-11 17:00:00'),
(12,NULL,'Phê duyệt bước tiếp cận cho Công ty Cổ phần Dược phẩm Pharmacity',3,5,'pending','2026-04-12 17:00:00'),
(13,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Vietful',4,5,'pending','2026-04-13 17:00:00'),
(16,NULL,'Phê duyệt bước tiếp cận cho Công ty TNHH Kootoro Việt Nam',2,5,'pending','2026-04-16 17:00:00'),
(18,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Eplus Research',4,5,'pending','2026-04-18 17:00:00'),
(19,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Dịch vụ Tư vấn Rapbank Việt Nam',5,5,'pending','2026-04-19 17:00:00'),
(20,NULL,'Phê duyệt bước tiếp cận cho CÔNG TY CỔ PHẦN SANAN',1,5,'pending','2026-04-20 17:00:00'),
(22,NULL,'Phê duyệt phương án / báo giá cho Tổng Công ty Máy động lực và Máy nông nghiệp Việt Nam - CTCP',3,5,'pending','2026-04-22 17:00:00'),
(24,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH CJ Olivenetworks Vina',5,5,'pending','2026-04-24 17:00:00'),
(25,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Vinsmart Future',1,5,'pending','2026-04-25 17:00:00'),
(26,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH An ninh An toàn Thông tin CMC',2,5,'pending','2026-04-26 17:00:00'),
(27,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH An ninh An toàn Thông tin CMC',3,5,'pending','2026-04-27 17:00:00'),
(28,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH An ninh An toàn Thông tin CMC',4,5,'pending','2026-04-28 17:00:00'),
(29,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Công nghệ Isofh',5,5,'pending','2026-04-01 17:00:00'),
(30,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Công nghệ Isofh',1,5,'pending','2026-04-02 17:00:00'),
(32,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Be Group',3,5,'pending','2026-04-04 17:00:00'),
(33,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Giải pháp Công nghệ Medx',4,5,'pending','2026-04-05 17:00:00'),
(34,NULL,'Phê duyệt phương án / báo giá cho Trung tâm Hỗ trợ Đấu thầu',5,5,'pending','2026-04-06 17:00:00'),
(35,NULL,'Phê duyệt phương án / báo giá cho Trung tâm Hỗ trợ Đấu thầu',1,5,'pending','2026-04-07 17:00:00'),
(36,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH NTT Data Việt Nam Solutions',2,5,'pending','2026-04-08 17:00:00'),
(37,NULL,'Phê duyệt phương án / báo giá cho Unloq International Company Limited',3,5,'pending','2026-04-09 17:00:00'),
(38,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Sinovnl',4,5,'pending','2026-04-10 17:00:00'),
(40,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Thu phí Tự động VETC',1,5,'pending','2026-04-12 17:00:00'),
(41,NULL,'Phê duyệt bước tiếp cận cho Tổng Công Ty Đầu Tư Phát Triển Đường Cao Tốc Việt Nam - Công Ty TNHH Một Thành Viên',2,5,'pending','2026-04-13 17:00:00'),
(42,NULL,'Phê duyệt phương án / báo giá cho Trung tâm Quản lý Luồng không lưu - Chi nhánh Tổng công ty Quản lý bay Việt Nam - Công ty TNHH',3,5,'pending','2026-04-14 17:00:00'),
(44,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Vĩnh Quang',5,5,'pending','2026-04-16 17:00:00'),
(46,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Cấp nước Thủ Đức',2,5,'pending','2026-04-18 17:00:00'),
(47,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Công nghệ KiotViet',3,5,'pending','2026-04-19 17:00:00'),
(49,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Công nghệ - Viễn thông Elcom',5,5,'pending','2026-04-21 17:00:00'),
(50,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Fiingroup Việt Nam',1,5,'pending','2026-04-22 17:00:00'),
(51,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Alinacom',2,5,'pending','2026-04-23 17:00:00'),
(52,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Giải pháp Hệ thống Long Vân',3,5,'pending','2026-04-24 17:00:00'),
(53,NULL,'Phê duyệt phương án / báo giá cho Trung tâm Dịch vụ Chuyển đổi số-Chi nhánh Tổng Công ty Công nghệ-Viễn thông Toàn cầu',4,5,'pending','2026-04-25 17:00:00'),
(58,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH NTT Data Việt Nam Solutions',4,5,'pending','2026-04-02 17:00:00'),
(59,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Orotech',5,5,'pending','2026-04-03 17:00:00'),
(60,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Orotech',1,5,'pending','2026-04-04 17:00:00'),
(61,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Orotech',2,5,'pending','2026-04-05 17:00:00'),
(63,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Đầu tư Kỹ thuật và Thương mại Thành Long',4,5,'pending','2026-04-07 17:00:00'),
(64,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Nature Story',5,5,'pending','2026-04-08 17:00:00'),
(65,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Tập đoàn Karofi',1,5,'pending','2026-04-09 17:00:00'),
(66,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH De Heus',2,5,'pending','2026-04-10 17:00:00'),
(67,NULL,'Phê duyệt bước tiếp cận cho Công ty TNHH Thương mại Dịch vụ Vexere',3,5,'pending','2026-04-11 17:00:00'),
(68,NULL,'Phê duyệt phương án / báo giá cho Báo công thương',4,5,'pending','2026-04-12 17:00:00'),
(69,NULL,'Phê duyệt phương án / báo giá cho Báo công thương',5,5,'pending','2026-04-13 17:00:00'),
(70,NULL,'Phê duyệt phương án / báo giá cho Báo công thương',1,5,'pending','2026-04-14 17:00:00'),
(71,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Quản lý Quỹ Bảo Việt',2,5,'pending','2026-04-15 17:00:00'),
(72,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Công nghệ Sapo',3,5,'pending','2026-04-16 17:00:00'),
(73,NULL,'Phê duyệt phương án / báo giá cho Net Protections',4,5,'pending','2026-04-17 17:00:00'),
(74,NULL,'Phê duyệt phương án / báo giá cho Ngân hàng Thương mại Cổ phần Xuất nhập khẩu Việt Nam',5,5,'pending','2026-04-18 17:00:00'),
(75,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Tổng Công ty Công nghệ và Giải pháp CMC',1,5,'pending','2026-04-19 17:00:00'),
(76,NULL,'Phê duyệt bước tiếp cận cho Công ty Cổ phần Funtap',2,5,'pending','2026-04-20 17:00:00'),
(77,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Insmart',3,5,'pending','2026-04-21 17:00:00'),
(78,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Điểm Sáng Công nghệ Investidea',4,5,'pending','2026-04-22 17:00:00'),
(79,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần VIEON',5,5,'pending','2026-04-23 17:00:00'),
(80,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần THS Game',1,5,'pending','2026-04-24 17:00:00'),
(81,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Sàn giao dịch Tài sản Mã hóa Lộc Phát Việt Nam',2,5,'pending','2026-04-25 17:00:00'),
(83,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Đầu tư Xây dựng và Kỹ thuật VNCN E&C',4,5,'pending','2026-04-27 17:00:00'),
(84,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Agent-X',5,5,'pending','2026-04-28 17:00:00'),
(85,NULL,'Phê duyệt phương án / báo giá cho Công ty Trách nhiệm hữu hạn Dự án Hồ Tràm',1,5,'pending','2026-04-01 17:00:00'),
(86,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Chứng khoán KIS Việt Nam',2,5,'pending','2026-04-02 17:00:00'),
(87,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Chứng khoán KIS Việt Nam',3,5,'pending','2026-04-03 17:00:00'),
(88,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Chứng khoán KIS Việt Nam',4,5,'pending','2026-04-04 17:00:00'),
(89,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần CMC OpenAI',5,5,'pending','2026-04-05 17:00:00'),
(90,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Nidec Việt Nam Corporation',1,5,'pending','2026-04-06 17:00:00'),
(91,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Nha khoa Kim',2,5,'pending','2026-04-07 17:00:00'),
(92,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH An ninh An toàn Thông tin CMC',3,5,'pending','2026-04-08 17:00:00'),
(93,NULL,'Phê duyệt phương án / báo giá cho Công ty Trách nhiệm hữu hạn Chứng khoán Ngân hàng Public Việt Nam',4,5,'pending','2026-04-09 17:00:00'),
(94,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Giải pháp số Mobifone',5,5,'pending','2026-04-10 17:00:00'),
(95,NULL,'Phê duyệt phương án / báo giá cho Tổng công ty Cổ phần Bảo hiểm Petrolimex',1,5,'pending','2026-04-11 17:00:00'),
(96,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Samsung SDS Việt Nam',2,5,'pending','2026-04-12 17:00:00'),
(97,NULL,'Phê duyệt phương án / báo giá cho Công Ty Cổ Phần Công Nghệ Kỹ Thuật Số - Hitd',3,5,'pending','2026-04-13 17:00:00'),
(98,NULL,'Phê duyệt phương án / báo giá cho Công Ty Cổ Phần Tiên Phong Invest',4,5,'pending','2026-04-14 17:00:00'),
(99,NULL,'Phê duyệt phương án / báo giá cho Công Ty Cổ Phần Tiên Phong Invest',5,5,'pending','2026-04-15 17:00:00'),
(100,NULL,'Phê duyệt phương án / báo giá cho Tổng công ty Bưu điện Việt Nam',1,5,'pending','2026-04-16 17:00:00'),
(101,NULL,'Phê duyệt phương án / báo giá cho Công Ty Cổ Phần Công Nghệ Nền Tảng Số Dtals',2,5,'pending','2026-04-17 17:00:00'),
(102,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH CMC Global',3,5,'pending','2026-04-18 17:00:00'),
(103,NULL,'Phê duyệt phương án / báo giá cho Công Ty Cổ Phần Pah Technology Việt Nam',4,5,'pending','2026-04-19 17:00:00'),
(104,NULL,'Phê duyệt phương án / báo giá cho Ngân hàng Thương mại Cổ phần Kiên Long',5,5,'pending','2026-04-20 17:00:00'),
(105,NULL,'Phê duyệt phương án / báo giá cho Ngân hàng Thương mại Cổ phần Kiên Long',1,5,'pending','2026-04-21 17:00:00'),
(106,NULL,'Phê duyệt phương án / báo giá cho Ngân hàng Thương mại Cổ phần Thịnh Vượng và Phát triển',2,5,'pending','2026-04-22 17:00:00'),
(107,NULL,'Phê duyệt phương án / báo giá cho Chương trình phát triển liên hiệp quốc (UNDP)',3,5,'pending','2026-04-23 17:00:00'),
(108,NULL,'Phê duyệt phương án / báo giá cho Cảng vụ Hàng không Miền Trung',4,5,'pending','2026-04-24 17:00:00'),
(109,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Dịch vụ Giải pháp Dữ liệu Trực tuyến Việt Nam',5,5,'pending','2026-04-25 17:00:00'),
(110,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Chứng Khoán Ngân hàng Thương mại cổ phần Ngoại thương Việt Nam',1,5,'pending','2026-04-26 17:00:00'),
(111,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Công nghệ Onelink Việt Nam',2,5,'pending','2026-04-27 17:00:00'),
(112,NULL,'Phê duyệt phương án / báo giá cho Cục Công nghệ thông tin và Chuyển đổi số',3,5,'pending','2026-04-28 17:00:00'),
(113,NULL,'Phê duyệt phương án / báo giá cho Công ty Cổ phần Vinschool',4,5,'pending','2026-04-01 17:00:00'),
(114,NULL,'Phê duyệt phương án / báo giá cho Công ty TNHH Xylentis',5,5,'pending','2026-04-02 17:00:00');
